name: docker-ci-node

on:
  repository_dispatch:
    types: [docker-ci-node]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          cd node
          docker build . --file Dockerfile --tag arbing/docker-ci-node:latest
      - name: Push the Docker image
        if: contains(github.event.action, 'docker-ci-node')
        run: |
          echo "${DOCKER_REGISTRY_PASSWORD}" | docker login -u ${DOCKER_REGISTRY_USER} --password-stdin
          docker push arbing/docker-ci-node:latest
        env:
          DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
          DOCKER_REGISTRY_USER: ${{secrets.DOCKER_REGISTRY_USER}}
          DOCKER_REGISTRY_PASSWORD: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
