name: oracle-jdk

on:
  repository_dispatch:
    types: [oracle-jdk]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          cd oracle-jdk
          docker build . --file Dockerfile --tag arbing/oracle-jdk:8
      - name: Push the Docker image
        if: contains(github.event.action, 'oracle-jdk')
        run: |
          echo "${DOCKER_REGISTRY_PASSWORD}" | docker login -u ${DOCKER_REGISTRY_USER} --password-stdin
          docker push arbing/oracle-jdk:8
        env:
          DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
          DOCKER_REGISTRY_USER: ${{secrets.DOCKER_REGISTRY_USER}}
          DOCKER_REGISTRY_PASSWORD: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
